apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: udacity-capstone-hello-app
  region: us-east-1
  tags:
    project: udacity-capstone-hello-app

iam:
  withOIDC: true

nodeGroups:
  - name: flask-hello-app
    instanceType: t2.small
    amiFamily: AmazonLinux2
    desiredCapacity: 1
    minSize: 1
    maxSize: 2
    volumeSize: 80
    ssh:
      allow: true
      publicKeyName: udacity