apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-hello-app
  labels:
    app: capstone-hello-app
  
spec:
  replicas: 3
  selector:
    matchLabels:
      app: capstone-hello-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: capstone-hello-app
    spec:
      containers:
        - image: sthirupws01/udacity-capstone
          imagePullPolicy: Always
          name: capstone-hello-app
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "128Mi"
              cpu: "500m"